### PR TITLE
Issue Tracker Helper

### PR DESCRIPTION
**Pull request by silamon**
Alternative for and as suggested in https://github.com/home-assistant/frontend/pull/21664

Completely untested. :smiley:

### CODE REVIEW

**Comment by joostlek** [comment]
Just as an FYI, you know that there is a saved reply feature in GitHub?

**Comment by frenck** [comment]
That is a good point... this is maybe more fit for saved replies instead. A bot isn't the most personal way either.

**Comment by silamon** [comment]
No, not really. Good thing to find out this way. 

I still think it's a good thing to merge. Too much time is spent triaging issues that don't belong to the issue tracker, even though there are guidelines to where to go if you have an issue related to that. For frontend, they don't even check off the checklist labels. Saved replies are also a personal thing, while these messages are only for a specific repository and of use for more maintainers.

**Comment by joostlek** [comment]
By the way, don't see this as "I don't care about triaging, good luck copy and pasting". I also like to triage every so often to make sure we don't have 10 issues for the same problem and to just know what's happening in the world.

I do like to discuss triaging and how we can improve that, I think @mib1185 also has some thoughts about this as he's also a common triager :)

**Comment by frenck** [comment]
From a pure functional perspective, using labeling to trigger replies and actions, is kinda misusing labeling IMHO.

These labels are now added to indicate a response, not the categorize the issue or pull request. I think that is wrong.

**Comment by joostlek** [comment]
Right, you have a point there. Although you could argue if an already fixed issue is a category. (I'm also still undecided about that)

**Comment by silamon** [comment]
I agree with the label use. With this PR, the labels also remain. 

Still, it would be great to have a good message that informs the user, without having to keep everything in sync.

**Comment by mib1185** [comment]
some more thoughts about the bot commands - we could distinguish between closing or just commenting 

commands:

- `@home-assistant close <message>`
- `@home-assistant comment <message>`

`<message>` is something of:

- `duplicate #xxxx` it is a duplicate of #xxxx (_link the issue_)
- `repo <REPONAME>` wrong repo, report it to `<REPONAME>` (_link the repo_)
- `fixed <VERSION>` already fixed in `<VERSION>` (_link the release_)

**Comment by joostlek** [comment]
I like the idea, but at that point you are already commenting, so might as well use a saved reply.

OTOH, I also notice that I am sometimes very short, I just say `Duplicate of #x` and close the issue. The only benefit I see with this is that we can add messages to provide more context to those short things. Like a "there's already an issue open for this issue with the same cause, yada yada, move to that issue please". But that might as well just be a saved reply as well.

**Comment by mib1185** [comment]
IMO the problem with saved replies is, that each one has to write its own saved replies, which leads to different _quality_ of context contained in the reply - for me i always try to add doc-links for things like "restart in safe mode" or "provide state details from dev-tools state tab" or "...wrong repo ... please report to REPONAME"

**Comment by joostlek** [comment]
But that's why I proposed a repo or gist to store these. We can even have some people who are good at writing have a look at them

**Comment by mib1185** [comment]
in the best case, the feature to provide saved replies per repo (_especial [this](https://github.com/orgs/community/discussions/4974#discussioncomment-6492401) approach_) will be implemented by github :crossed_fingers: :see_no_evil: 
Having a repo or gist with saved reply templates is much better than nothing and would already help to improve the quality of context of triage comments :+1:

**Comment by joostlek** [comment]
I think that would be the ultimate solution to automatically bootstrap everyone with the right saved replies etc

**Pull request closed without merging**
